### ISSUE TITLE
Build error due to missing crc32table.h

### ISSUE THREAD

**Issue by nfeske** [skalk/genode-imx8mq#1]
When attempting to build the framebuffer or SD-card driver, the following error occurs:

```
.../contrib/mnt_reform2_linux-90fc608b70814e0448031ad49a99273ed72d77a4/linux/lib/crc32.c:48:10: fatal error: crc32table.h: No such file or directory
   48 | #include "crc32table.h"
```

This file is normally generated by the Linux build system but it is absent from src/include/imx8mq/lx_generated. BTW, for the genode-allwinner drivers, I use the following rule to generate the file: https://github.com/nfeske/genode-allwinner/blob/master/lib/import/import-a64_lx_emul.mk#L147

**Comment by skalk** [comment]
That is somehow strange. While working on the common code base of both drivers (sd_card and framebuffer), I realized that I accidentally removed that header, but certainly re-added it. Now, I'm quite puzzled during which rebase action it got lost again.

I'm sorry for any inconvenience it introduced to you. Thank you for reporting it.
